#### database main task  ####
---
  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
  - name: Install mysql-server
    apt:
      name: mysql-server
      update_cache: yes
